#!/usr/bin/env python3
"""Convert snes/font8x8_basic.h (public-domain 8x8 font, bit 0 = leftmost
pixel) into SNES 2bpp tiles as a C array.

Emits 192 tiles: tiles 0-95 are ASCII 0x20-0x7F drawn with pixel value 1
(normal text), tiles 96-191 are the same glyphs with plane 1 forced on, so
set pixels read 3 and clear pixels 2 (highlight/inverted, e.g. the on-screen
keyboard cursor). Palette: c0 backdrop, c1 text, c2 highlight bg, c3
highlight fg. Usage: font2snes.py snes/font8x8_basic.h out.c
"""
import re
import sys


def parse_font(path):
    glyphs = []
    for m in re.finditer(r"\{\s*((?:0x[0-9A-Fa-f]{2}\s*,\s*){7}0x[0-9A-Fa-f]{2})\s*\}", open(path).read()):
        rows = [int(b, 16) for b in re.findall(r"0x[0-9A-Fa-f]{2}", m.group(1))]
        glyphs.append(rows)
    assert len(glyphs) == 128, f"expected 128 glyphs, got {len(glyphs)}"
    return glyphs


def bitrev8(b):
    return int(f"{b:08b}"[::-1], 2)


def tile_2bpp(rows, plane1):
    out = []
    for r in rows:
        p0 = bitrev8(r)  # font bit 0 = left; SNES bit 7 = left
        out += [p0, plane1]
    return out


def main(src, dst):
    glyphs = parse_font(src)
    data = []
    for plane1 in (0x00, 0xFF):
        for code in range(0x20, 0x80):
            data += tile_2bpp(glyphs[code], plane1)
    with open(dst, "w") as f:
        f.write("// Generated by tools/font2snes.py from snes/font8x8_basic.h"
                " (public domain).\n// 192 SNES 2bpp tiles: ASCII 0x20-0x7F"
                " normal (0-95) and highlighted (96-191).\n")
        f.write(f"const unsigned char snes_font2bpp[{len(data)}] = {{\n")
        for i in range(0, len(data), 16):
            f.write("    " + ",".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",\n")
        f.write("};\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
