#!/usr/bin/env python3
"""Generate port/pylib/stage_assets.py: a Stage tile bank for the demo.

Stage bank format: 16 tiles of 16x16 pixels, 4bpp packed (even x = high
nibble), 2048 bytes total; palette = 16x RGB565 stored big-endian (32
bytes), entry 0 is the transparent color (Stage convention: magic pink).
Drawn here on the host because filling 2048 bytes pixel-by-pixel in
Python on a 3.58MHz 65816 would take minutes of boot time.
"""
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "port/pylib/stage_assets.py"

# palette index -> RGB565
PAL = [
    0xf81f,  # 0 transparent (magic pink)
    0x0000,  # 1 black
    0xffff,  # 2 white
    0x8410,  # 3 gray
    0x2104,  # 4 dark gray
    0xf800,  # 5 red
    0x8000,  # 6 dark red
    0x07e0,  # 7 green
    0x0320,  # 8 dark green
    0x001f,  # 9 blue
    0x0010,  # 10 dark blue
    0xffe0,  # 11 yellow
    0xfc00,  # 12 orange
    0x07ff,  # 13 cyan
    0x8a86,  # 14 brown
    0xd69a,  # 15 light gray
]

tiles = [[[0] * 16 for _ in range(16)] for _ in range(16)]


def ball(t, body, dark, shine=2):
    """A shaded ball with outline into tile t."""
    for y in range(16):
        for x in range(16):
            dx, dy = x - 7.5, y - 7.5
            d2 = dx * dx + dy * dy
            if d2 <= 42:
                sx, sy = x - 5, y - 5
                if d2 >= 30:
                    tiles[t][y][x] = dark
                elif sx * sx + sy * sy <= 3:
                    tiles[t][y][x] = shine
                else:
                    tiles[t][y][x] = body


def wall(t):
    """Brick wall: 8px-high courses, staggered joints, gray mortar."""
    for y in range(16):
        for x in range(16):
            c = 5 if (x + y) % 9 else 6  # brick red, a little texture
            if y % 8 == 7:
                c = 3  # horizontal mortar
            else:
                joint = 7 if (y // 8) % 2 == 0 else 15
                if x % 8 == joint % 8 and joint < 16:
                    c = 3  # vertical mortar, staggered per course
            tiles[t][y][x] = c


def floor_dots(t):
    """Nearly-black floor with a dim dot grid."""
    for y in range(16):
        for x in range(16):
            tiles[t][y][x] = 4 if (x % 8 == 3 and y % 8 == 3) else 1


wall(1)
floor_dots(2)
ball(3, 5, 6)    # red
ball(4, 9, 10)   # blue
ball(5, 11, 12)  # yellow

buf = bytearray(2048)
for t in range(16):
    for y in range(16):
        for x in range(16):
            i = t * 128 + y * 8 + (x >> 1)
            p = tiles[t][y][x] & 0x0F
            if x & 1:
                buf[i] |= p
            else:
                buf[i] |= p << 4

pal = bytearray()
for c in PAL:
    pal += bytes((c >> 8, c & 0xFF))


def blit(name, data, out):
    out.write(name + " = (\n")
    for i in range(0, len(data), 16):
        out.write("    %r\n" % bytes(data[i:i + 16]))
    out.write(")\n")


with OUT.open("w") as f:
    f.write('"""Demo assets, generated by tools/gen_stage_assets.py."""\n')
    f.write("# tiles: 0 empty, 1 brick wall, 2 floor, 3/4/5 red/blue/yellow ball\n")
    blit("BANK", buf, f)
    blit("PALETTE", pal, f)

print(f"wrote {OUT} ({len(buf)} bank bytes)", file=sys.stderr)
